### ISSUE TITLE
Units not shown

### ISSUE THREAD

**Issue by jidanni** [DamnBack/locate-points#1]
We see a box for distance and a box for offset, but next to them there is no "KM", "degrees" etc.
All we can do is cross our fingers.

**Comment by jidanni** [comment]
OK, maybe have it say e.g., "degrees (from coordinate system)" else the
user will think the author only likes degrees, feet, etc.

**Comment by DamnBack** [comment]
Added units as an offset and interval tool tip in 0.3.4 plugin version.
