### ISSUE TITLE
Points not rendering (?)

### ISSUE THREAD

**Issue by vincemazz17** [DamnBack/locate-points#3]
Using against a very basic vector layer, I was (a couple times) successful with creating points along lines - then had an unprovoked system error that shut down the application. Now, the macro runs but no points are visible. Tried various options. Attribute table loads successfully as it did before. Advice? Win 8.1 x64

Thanks

**Comment by DamnBack** [comment]
Hi @vincemazz17 
Please try to update plugin to the latest version (0.3.1) and check if issue still appears.
Best regards,
Łukasz Dębek
